# Generated by Django 4.0.5 on 2023-01-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_auto_20210511_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Subject Image'),
        ),
    ]
