# Generated by Django 4.0.5 on 2023-01-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_standard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
