# Generated by Django 4.0.5 on 2023-01-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_alter_standard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images/'),
        ),
    ]
