# Generated by Django 4.0.5 on 2023-01-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0033_alter_standard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Images/'),
        ),
    ]
